In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.core.operations import SymmOp
from pymatgen.io.cif import *
from pymatgen.core.operations import *
from tabulate import tabulate
from pymatgen.symmetry.site_symmetries import *
import matplotlib.pyplot as plt
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view

In [2]:
mp_key = "u9ZAHMoFazUCz7neZTBfXBwCZ5RESH4Z"
mp_id = "mp-567636"

In [3]:
structure = MPRester(mp_key).get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
print("structure de la maille")
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('rotate on')

structure de la maille


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [5]:
print("nb d'atomes: " + str(len(conv_struc.sites)-1))

#les 3 opérations de symetries et les 3 atomes
i_atom1, i_atom2, i_atom3 = 5,7,2
i_symmop1, i_symmop2, i_symmop3 = 3,4,11
print(symmops)

nb d'atomes: 11
F-43m (216) spacegroup


In [6]:
#première symétrie
symmop1 = symmops[i_symmop1 - 1]
print("rotation C2 sans translation (autour de l'axe [1, 1, 1]) \n")
print("La matrices de rotation et le vecteur de translation sont")
print(symmop1,"\n")

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom1 -1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop1.operate(pos_init)
print(pos_final,"\n")

#ce code parcourt tous les atomes de la structure atomique, compare leurs coordonnées 
#fractionnaires avec une position finale, et imprime les coordonnées de l'atome correspondant s'il est trouvé.
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

view1 = quick_view(structure, "packed", conventional = True)
display(view1)
view1.script('draw SYMOP ' + str(i_symmop1) + ' {atomno = ' + str(i_atom1) + '}')

rotation C2 sans translation (autour de l'axe [1, 1, 1]) 

La matrices de rotation et le vecteur de translation sont
Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.] 

Les coordonnées initial de l'atome sont
[0.75 0.25 0.75] 

Apres l'opération de symmétrie, ces coordonnées sont
[-0.75 -0.25  0.75] 

8 [0.25 0.75 0.75]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [7]:
#deuxième symétrie
symmop2 = symmops[i_symmop2 - 1]
print("rotation C4 sans rotation (autour de l'axe [0, 0, 1]) \n")
print("La matrices de rotation et le vecteur de translation sont")
print(symmop2,"\n")

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom2 -1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop2.operate(pos_init)
print(pos_final,"\n")

#ce code parcourt tous les atomes de la atomique, compare leurs coordonnées 
#fractionnaires avec une position finale, et imprime les coordonnées de l'atome correspondant s'il est trouvé.
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

view2 = quick_view(structure, "packed", conventional = True)
display(view2)
view2.script('draw SYMOP ' + str(i_symmop2) + ' {atomno = ' + str(i_atom2) + '}')

rotation C4 sans rotation (autour de l'axe [0, 0, 1]) 

La matrices de rotation et le vecteur de translation sont
Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Les coordonnées initial de l'atome sont
[0.25 0.25 0.25] 

Apres l'opération de symmétrie, ces coordonnées sont
[-0.25  0.25 -0.25] 

5 [0.75 0.25 0.75]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [8]:
#troisième symétrie
symmop3 = symmops[i_symmop3 - 1]
print("rotation C3 sans translation (autour de l'axe [1, 1, 1])")
print("La matrices de rotation et le vecteur de translation sont")
print(symmop3,"\n")

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom3 - 1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop3.operate(pos_init)
print(pos_final,"\n")

#ce code parcourt tous les atomes de la structure atomique, compare leurs coordonnées 
#fractionnaires avec une position finale, et imprime les coordonnées de l'atome correspondant s'il est trouvé.
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

view3 = quick_view(conv_struc, "packed", conventional = True)
display(view3)
view3.script('draw SYMOP ' + str(i_symmop3) + ' {atomno = ' + str(i_atom3) + '}')

rotation C3 sans translation (autour de l'axe [1, 1, 1])
La matrices de rotation et le vecteur de translation sont
Rot:
[[ 0.  0.  1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]
tau
[0. 0. 0.] 

Les coordonnées initial de l'atome sont
[0.  0.5 0.5] 

Apres l'opération de symmétrie, ces coordonnées sont
[ 0.5  0.  -0.5] 

3 [0.5 0.  0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))